
name: Documentation

on:
  push

jobs:

  deploy:
    name: Deploy documentation
    runs-on: ubuntu-latest
    container: falken05/margitdocker
    steps:
    - uses: actions/checkout@v2    
    - run: doxygen doxconf
    - run: cd DOCS/latex && make
    
    - name: Generate artifact
      uses: actions/upload-artifact@v2
      with:
        name: html-and-pdf-download
        path: DOCS

    - name: Push git subdir as branch
      uses: s0/git-publish-subdir-action@v2.4.0

      env:
        REPO: self
        BRANCH: documentation
        FOLDER: DOCS/html
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}